#!/bin/bash

# Accepts only a filepath to the "*.in" file and outputs results to stdout
if [[ $# -ne 1 ]]; then
    echo "usage: gen-in FILE" >&2
    exit 1
fi

IN_FILE="$1"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

APP_NAME=napiman

sed -e "s|@PACKAGE_NAME[@]|$APP_NAME|g" \
    -e "s|@VERSION[@]|$($SCRIPT_DIR/gen-version)|g" \
    $IN_FILE
