#!/bin/bash

# Accepts only a filepath to the "*.in" file and outputs results to stdout
if [[ $# -ne 1 ]]; then
    echo "usage: gen-in FILE" >&2
    exit 1
fi

in_file="$1"
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

app_name=${NAPIMAN_APP_NAME:=napiman}
venv_dir=${NAPIMAN_VENV_DIR:=.venv}

sed -e "s|@PACKAGE_NAME[@]|$app_name|g" \
    -e "s|@VERSION[@]|$($script_dir/gen-version)|g" \
    -e "s|@NAPIMAN_DIR[@]|$(dirname $script_dir)|g" \
    -e "s|@VENV_DIR[@]|$venv_dir|g" \
    $in_file
